### ISSUE TITLE
Opening python files from source control auto opens Explorer view

### ISSUE THREAD

**Issue by aaronrai24** [keith-gamble/ignition-flint#4]
Opening to view source control changes from here:

<img width="475" alt="image" src="https://github.com/keith-gamble/ignition-flint/assets/55159220/72984c73-e6e2-4540-9f0b-280dd4bdf5e3">

Shoots you into this view:
![image](https://github.com/keith-gamble/ignition-flint/assets/55159220/2ece085b-d32e-412d-b463-b7b400e466b7)

**Comment by keith-gamble** [comment]
This has been resolved in version v0.0.19
